# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-31 06:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ORIGIN', 'At Origin'), ('ENROUTE', 'Enroute'), ('DESTINATION', 'At Destination'), ('REFUSED', 'Refused Delivery'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled Shipment'), ('LATE', 'Late')], default='ORIGIN', max_length=30)),
                ('sender', models.CharField(max_length=30)),
                ('recipient', models.CharField(max_length=30)),
                ('carrier', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_ship_date', models.DateTimeField(default=datetime.datetime(2018, 8, 3, 6, 10, 19, 594466))),
                ('origin', models.CharField(max_length=40)),
                ('origin_address', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=40)),
                ('destination_address', models.CharField(max_length=100)),
                ('total_weight', models.CharField(max_length=6)),
                ('total_volume', models.CharField(max_length=6)),
            ],
        ),
    ]
