# Generated by Django 2.0.7 on 2018-07-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ORIGIN', 'At Origin'), ('ENROUTE', 'Enroute'), ('DESTINATION', 'At Destination'), ('REFUSED', 'Refused Delivery'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled Shipment'), ('LATE', 'Late')], default='ORIGIN', max_length=30)),
                ('recipient', models.CharField(max_length=30)),
                ('carrier', models.CharField(max_length=15)),
                ('expected_ship_date', models.DateField()),
                ('origin', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=40)),
                ('total_weight', models.CharField(max_length=6)),
                ('total_volume', models.CharField(max_length=6)),
            ],
        ),
    ]
