# Generated by Django 2.0.7 on 2018-07-31 00:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='expected_ship_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 0, 41, 55, 687682)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recipient',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_volume',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_weight',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
