# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-31 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='expected_ship_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 3, 11, 42, 21, 499236)),
        ),
    ]
